version: "3"
services:
  db:
    image: postgres:10
    restart: always
    container_name: db-apollo
    ports:
      - "5432:5432"
    volumes:
      - db-apollo:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db-apollo:
